language: go
go:
- tip
install:
- gem install fpm
script:
- "./scripts/build.sh"
before_deploy:
- "./scripts/package.sh"
- "./scripts/release.sh"
deploy:
  provider: releases
  api_key:
    secure: eHqmXmT9ziWulQzQB05fZu1W8O6Ox31TTc0kgdAuUIgT03jKFk7/SMmwgN8gLlnPUo0vdkwXI/ZUWQSv7x/euNejLLOBl2ZnJ3siG2kfkQikvGZvUWhqKhLmbWq01dak+nXW4FApJctDH7lIZytCY/lY2YqxRKEI+Rn1f/ec9v0=
  files:
  - "./pkg/linux/hello-linux-0.0.1-1.x86_64.rpm"
  on:
    tags: true
  skip_cleanup: true
addons:
  apt_packages:
  - rpm
env:
  global:
    secure: Yrn5VJXIZkzRpvwb20IyC7OAQyyQaG+80L8O9VC7zeXrf8McCXadEyPMXQ3dzuaz8T1Ns6xkrZryPs1Yhp02g5Bz9vIUqbL3GsdyFKI6BixWLbpIz6o1GET2XkvPfp175PrOilKD8vw+4ge8figp3juW99mdzX+FCIe9Zmb9nQo=
