language: go
go:
  - tip
install:
 - gem install fpm
 # - source ./scripts/golang.sh
script:
 - ./scripts/build.sh
 - ./scripts/package.sh
addons:
  apt_packages:
  - gcc
  - libc6-dev
  - libc6-dev-i386
env:
- GIMME_OS=linux GIMME_ARCH=amd64
- GIMME_OS=darwin GIMME_ARCH=amd64
- GIMME_OS=windows GIMME_ARCH=amd64
